"""
Seed the database with vocabulary from "Sėkmės!" Lithuanian textbook (1st book).
Each word list corresponds to a chapter's Žodynas (vocabulary) section.

Run from backend/ directory:
    python seed.py
"""
import os
import sys
from dotenv import load_dotenv

load_dotenv()

from sqlmodel import Session, select
from database import engine, create_db_and_tables
from models import Word, WordList, WordListItem

create_db_and_tables()

# Format: (lithuanian, translation_en, translation_ru, hint)
WORD_LISTS = [
    {
        "title": "1. Koks jūsų vardas?",
        "description": "Countries, nationalities and basic vocabulary (Žodynas)",
        "words": [
            # Countries & nationalities (šalis, gyventojas, gyventoja)
            ("Amerika", "America", "Америка", "šalis"),
            ("amerikietis / amerikietė", "American (m./f.)", "американец / американка", "tauta"),
            ("Anglija", "England", "Англия", "šalis"),
            ("anglas / anglė", "English (m./f.)", "англичанин / англичанка", "tauta"),
            ("Airija", "Ireland", "Ирландия", "šalis"),
            ("airis / airė", "Irish (m./f.)", "ирландец / ирландка", "tauta"),
            ("Baltarusija", "Belarus", "Беларусь", "šalis"),
            ("baltarusis / baltarusė", "Belarusian (m./f.)", "белорус / белоруска", "tauta"),
            ("Brazilija", "Brazil", "Бразилия", "šalis"),
            ("brazilas / brazilė", "Brazilian (m./f.)", "бразилец / бразильянка", "tauta"),
            ("Belgija", "Belgium", "Бельгия", "šalis"),
            ("belgas / belgė", "Belgian (m./f.)", "бельгиец / бельгийка", "tauta"),
            ("Čekija", "Czech Republic", "Чехия", "šalis"),
            ("čekas / čekė", "Czech (m./f.)", "чех / чешка", "tauta"),
            ("Čilė", "Chile", "Чили", "šalis"),
            ("čilietis / čilietė", "Chilean (m./f.)", "чилиец / чилийка", "tauta"),
            ("Danija", "Denmark", "Дания", "šalis"),
            ("danas / danė", "Danish (m./f.)", "датчанин / датчанка", "tauta"),
            ("Estija", "Estonia", "Эстония", "šalis"),
            ("estas / estė", "Estonian (m./f.)", "эстонец / эстонка", "tauta"),
            ("Filipinai", "Philippines", "Филиппины", "šalis"),
            ("filipinietis / filipinietė", "Filipino (m./f.)", "филиппинец / филиппинка", "tauta"),
            ("Graikija", "Greece", "Греция", "šalis"),
            ("graikas / graikė", "Greek (m./f.)", "грек / гречанка", "tauta"),
            ("Havajai", "Hawaii", "Гавайи", "šalis"),
            ("havajietis / havajietė", "Hawaiian (m./f.)", "гавайец / гавайка", "tauta"),
            ("Ispanija", "Spain", "Испания", "šalis"),
            ("ispanas / ispanė", "Spanish (m./f.)", "испанец / испанка", "tauta"),
            ("Italija", "Italy", "Италия", "šalis"),
            ("italas / italė", "Italian (m./f.)", "итальянец / итальянка", "tauta"),
            ("Izraelis", "Israel", "Израиль", "šalis"),
            ("izraelietis / izraelietė", "Israeli (m./f.)", "израильтянин / израильтянка", "tauta"),
            ("Japonija", "Japan", "Япония", "šalis"),
            ("japonas / japonė", "Japanese (m./f.)", "японец / японка", "tauta"),
            ("Kanada", "Canada", "Канада", "šalis"),
            ("kanadietis / kanadietė", "Canadian (m./f.)", "канадец / канадка", "tauta"),
            ("Kinija", "China", "Китай", "šalis"),
            ("kinas / kinė", "Chinese (m./f.)", "китаец / китаянка", "tauta"),
            ("Lietuva", "Lithuania", "Литва", "šalis"),
            ("lietuvis / lietuvė", "Lithuanian (m./f.)", "литовец / литовка", "tauta"),
            ("Lenkija", "Poland", "Польша", "šalis"),
            ("lenkas / lenkė", "Polish (m./f.)", "поляк / полька", "tauta"),
            ("Moldova", "Moldova", "Молдова", "šalis"),
            ("moldavas / moldavė", "Moldovan (m./f.)", "молдаванин / молдаванка", "tauta"),
            ("Norvegija", "Norway", "Норвегия", "šalis"),
            ("norvegas / norvegė", "Norwegian (m./f.)", "норвежец / норвежка", "tauta"),
            ("Olandija", "Netherlands", "Нидерланды", "šalis"),
            ("olandas / olandė", "Dutch (m./f.)", "голландец / голландка", "tauta"),
            ("Portugalija", "Portugal", "Португалия", "šalis"),
            ("portugalas / portugalė", "Portuguese (m./f.)", "португалец / португалка", "tauta"),
            ("Prancūzija", "France", "Франция", "šalis"),
            ("prancūzas / prancūzė", "French (m./f.)", "француз / француженка", "tauta"),
            ("Rusija", "Russia", "Россия", "šalis"),
            ("rusas / rusė", "Russian (m./f.)", "русский / русская", "tauta"),
            ("Slovakija", "Slovakia", "Словакия", "šalis"),
            ("slovakas / slovakė", "Slovak (m./f.)", "словак / словачка", "tauta"),
            ("Slovėnija", "Slovenia", "Словения", "šalis"),
            ("slovėnas / slovėnė", "Slovenian (m./f.)", "словенец / словенка", "tauta"),
            ("Suomija", "Finland", "Финляндия", "šalis"),
            ("suomis / suomė", "Finnish (m./f.)", "финн / финка", "tauta"),
            ("Švedija", "Sweden", "Швеция", "šalis"),
            ("švedas / švedė", "Swedish (m./f.)", "швед / шведка", "tauta"),
            ("Turkija", "Turkey", "Турция", "šalis"),
            ("turkas / turkė", "Turkish (m./f.)", "турок / турчанка", "tauta"),
            ("Ukraina", "Ukraine", "Украина", "šalis"),
            ("ukrainietis / ukrainietė", "Ukrainian (m./f.)", "украинец / украинка", "tauta"),
            ("Urugvajus", "Uruguay", "Уругвай", "šalis"),
            ("urugvajietis / urugvajietė", "Uruguayan (m./f.)", "уругваец / уругвайка", "tauta"),
            ("Vengrija", "Hungary", "Венгрия", "šalis"),
            ("vengras / vengrė", "Hungarian (m./f.)", "венгр / венгерка", "tauta"),
            ("Vokietija", "Germany", "Германия", "šalis"),
            ("vokietis / vokietė", "German (m./f.)", "немец / немка", "tauta"),
            ("Zimbabvė", "Zimbabwe", "Зимбабве", "šalis"),
            ("Sakartvelas", "Georgia (country)", "Грузия", "šalis"),
            ("kartvelas / kartvelė", "Georgian (m./f.)", "грузин / грузинка", "tauta"),
            # Basic vocabulary
            ("būti, yra, buvo", "to be", "быть", "veiksmažodis"),
            ("nebūti, nėra, nebuvo", "not to be", "не быть", "veiksmažodis"),
            ("taip", "yes", "да", None),
            ("ne", "no", "нет", None),
            ("čia", "here", "здесь", None),
            ("ir", "and", "и", "jungtukas"),
            ("o", "and / but", "а / но", "jungtukas"),
            ("dėstytojas / dėstytoja", "university teacher (m./f.)", "преподаватель / преподавательница", "daiktavardis"),
            ("studentas / studentė", "student (m./f.)", "студент / студентка", "daiktavardis"),
            ("vardas", "name", "имя", "daiktavardis"),
            ("pavardė", "surname", "фамилия", "daiktavardis"),
        ],
    },
    {
        "title": "2. Čia mano draugas",
        "description": "People, greetings and languages (Žodynas)",
        "words": [
            ("kalbėti, kalba, kalbėjo", "to speak", "говорить", "veiksmažodis"),
            ("suprasti, supranta, suprato", "to understand", "понимать", "veiksmažodis"),
            ("bet", "but", "но", "jungtukas"),
            ("blogai", "bad / badly", "плохо", "prieveiksmis"),
            ("gerai", "good / fine / well", "хорошо", "prieveiksmis"),
            ("šiaip sau", "so-so", "так себе", "prieveiksmis"),
            ("taip pat", "as well / too", "тоже", "prieveiksmis"),
            ("truputį", "a little (bit)", "немного / чуть-чуть", "prieveiksmis"),
            ("ponas", "Mr", "господин", "daiktavardis"),
            ("ponia", "Mrs / Ms", "госпожа", "daiktavardis"),
            ("draugas / draugė", "friend (m./f.)", "друг / подруга", "daiktavardis"),
        ],
    },
    {
        "title": "3. Koks tavo adresas?",
        "description": "Numbers, city places and addresses (Žodynas)",
        "words": [
            # Numbers
            ("nulis", "zero", "ноль", "skaitvardis"),
            ("vienas", "one", "один", "skaitvardis"),
            ("du", "two", "два", "skaitvardis"),
            ("trys", "three", "три", "skaitvardis"),
            ("keturi", "four", "четыре", "skaitvardis"),
            ("penki", "five", "пять", "skaitvardis"),
            ("šeši", "six", "шесть", "skaitvardis"),
            ("septyni", "seven", "семь", "skaitvardis"),
            ("aštuoni", "eight", "восемь", "skaitvardis"),
            ("devyni", "nine", "девять", "skaitvardis"),
            ("dešimt", "ten", "десять", "skaitvardis"),
            ("vienuolika", "eleven", "одиннадцать", "skaitvardis"),
            ("dvylika", "twelve", "двенадцать", "skaitvardis"),
            ("trylika", "thirteen", "тринадцать", "skaitvardis"),
            ("keturiolika", "fourteen", "четырнадцать", "skaitvardis"),
            ("penkiolika", "fifteen", "пятнадцать", "skaitvardis"),
            ("šešiolika", "sixteen", "шестнадцать", "skaitvardis"),
            ("septyniolika", "seventeen", "семнадцать", "skaitvardis"),
            ("aštuoniolika", "eighteen", "восемнадцать", "skaitvardis"),
            ("devyniolika", "nineteen", "девятнадцать", "skaitvardis"),
            ("dvidešimt", "twenty", "двадцать", "skaitvardis"),
            ("trisdešimt", "thirty", "тридцать", "skaitvardis"),
            ("keturiasdešimt", "forty", "сорок", "skaitvardis"),
            ("penkiasdešimt", "fifty", "пятьдесят", "skaitvardis"),
            ("šešiasdešimt", "sixty", "шестьдесят", "skaitvardis"),
            ("septyniasdešimt", "seventy", "семьдесят", "skaitvardis"),
            ("aštuoniasdešimt", "eighty", "восемьдесят", "skaitvardis"),
            ("devyniasdešimt", "ninety", "девяносто", "skaitvardis"),
            ("šimtas", "one hundred", "сто", "skaitvardis"),
            # Verbs
            ("gyventi, gyvena, gyveno", "to live", "жить", "veiksmažodis"),
            ("dirbti, dirba, dirbo", "to work", "работать", "veiksmažodis"),
            ("studijuoti, studijuoja, studijavo", "to study", "учиться / изучать", "veiksmažodis"),
            # People
            ("bendradarbis / bendradarbė", "colleague (m./f.)", "коллега", "daiktavardis"),
            ("kaimynas / kaimynė", "neighbour (m./f.)", "сосед / соседка", "daiktavardis"),
            # City & places
            ("sostinė", "capital (city)", "столица", "daiktavardis"),
            ("miestas", "city / town", "город", "daiktavardis"),
            ("centras", "centre", "центр", "daiktavardis"),
            ("senamiestis", "old town", "старый город", "daiktavardis"),
            ("adresas", "address", "адрес", "daiktavardis"),
            ("telefonas", "telephone", "телефон", "daiktavardis"),
            ("namas", "house / building", "дом", "daiktavardis"),
            ("butas", "apartment / flat", "квартира", "daiktavardis"),
            ("kambarys", "room", "комната", "daiktavardis"),
            ("bendrabutis", "dormitory", "общежитие", "daiktavardis"),
            ("viešbutis", "hotel", "гостиница", "daiktavardis"),
            ("bažnyčia", "church", "церковь", "daiktavardis"),
            ("ambasada", "embassy", "посольство", "daiktavardis"),
            ("bankas", "bank", "банк", "daiktavardis"),
            ("paštas", "post office", "почта", "daiktavardis"),
            ("ministerija", "ministry", "министерство", "daiktavardis"),
            ("biuras", "office / bureau", "офис / бюро", "daiktavardis"),
            ("universitetas", "university", "университет", "daiktavardis"),
            ("mokykla", "school", "школа", "daiktavardis"),
            ("vaikų darželis", "nursery school / kindergarten", "детский сад", "daiktavardis"),
            ("biblioteka", "library", "библиотека", "daiktavardis"),
            ("knygynas", "bookstore", "книжный магазин", "daiktavardis"),
            ("restoranas", "restaurant", "ресторан", "daiktavardis"),
            ("baras", "bar", "бар", "daiktavardis"),
            ("kavinė", "cafe", "кафе", "daiktavardis"),
            ("valgykla", "canteen", "столовая", "daiktavardis"),
            ("prekybos centras", "shopping centre", "торговый центр", "daiktavardis"),
            ("parduotuvė", "shop / store", "магазин", "daiktavardis"),
            ("kioskas", "kiosk", "киоск", "daiktavardis"),
            ("turgus", "market", "рынок", "daiktavardis"),
            ("kirpykla", "hairdresser's", "парикмахерская", "daiktavardis"),
            ("grožio salonas", "beauty salon", "салон красоты", "daiktavardis"),
            ("kino teatras", "cinema", "кинотеатр", "daiktavardis"),
            ("teatras", "theatre", "театр", "daiktavardis"),
            ("muziejus", "museum", "музей", "daiktavardis"),
            ("pilis", "castle", "замок", "daiktavardis"),
            ("sporto klubas", "gym / sports club", "спортивный клуб", "daiktavardis"),
            ("ligoninė", "hospital", "больница", "daiktavardis"),
            ("klinika", "clinic", "клиника", "daiktavardis"),
            ("vaistinė", "pharmacy", "аптека", "daiktavardis"),
            ("gatvė", "street", "улица", "daiktavardis"),
            ("alėja", "alley / boulevard", "аллея", "daiktavardis"),
            ("prospektas", "avenue / prospect", "проспект", "daiktavardis"),
            ("aikštė", "square", "площадь", "daiktavardis"),
            ("oro uostas", "airport", "аэропорт", "daiktavardis"),
            ("stotis", "station", "станция / вокзал", "daiktavardis"),
            ("autobusų stotis", "bus station", "автобусный вокзал", "daiktavardis"),
            ("geležinkelio stotis", "railway station", "железнодорожный вокзал", "daiktavardis"),
            ("stotelė", "bus/tram stop", "остановка", "daiktavardis"),
            ("darbas", "work / job", "работа", "daiktavardis"),
            ("upė", "river", "река", "daiktavardis"),
            ("tiltas", "bridge", "мост", "daiktavardis"),
            ("ežeras", "lake", "озеро", "daiktavardis"),
            ("jūra", "sea", "море", "daiktavardis"),
            ("parkas", "park", "парк", "daiktavardis"),
            ("miškas", "forest / woods", "лес", "daiktavardis"),
            ("arti", "near / close", "близко / рядом", "prieveiksmis"),
            ("toli", "far", "далеко", "prieveiksmis"),
            ("namie", "at home", "дома", "prieveiksmis"),
        ],
    },
    {
        "title": "4. Kada ir kur susitinkame?",
        "description": "Days of the week, time and time expressions (Žodynas)",
        "words": [
            # Week
            ("savaitė", "week", "неделя", "daiktavardis"),
            ("pirmadienis", "Monday", "понедельник", "daiktavardis"),
            ("antradienis", "Tuesday", "вторник", "daiktavardis"),
            ("trečiadienis", "Wednesday", "среда", "daiktavardis"),
            ("ketvirtadienis", "Thursday", "четверг", "daiktavardis"),
            ("penktadienis", "Friday", "пятница", "daiktavardis"),
            ("šeštadienis", "Saturday", "суббота", "daiktavardis"),
            ("sekmadienis", "Sunday", "воскресенье", "daiktavardis"),
            ("savaitgalis", "weekend", "выходные", "daiktavardis"),
            # Time adverbs
            ("šiandien", "today", "сегодня", "prieveiksmis"),
            ("rytoj", "tomorrow", "завтра", "prieveiksmis"),
            ("kartais", "sometimes", "иногда", "prieveiksmis"),
            ("retai", "seldom / rarely", "редко", "prieveiksmis"),
            ("dažnai", "often", "часто", "prieveiksmis"),
            ("visada", "always", "всегда", "prieveiksmis"),
            ("niekada", "never", "никогда", "prieveiksmis"),
            ("kasdien", "every day", "каждый день", "prieveiksmis"),
            # Time words
            ("valanda", "hour / o'clock", "час", "daiktavardis"),
            ("pusė", "half", "половина", "daiktavardis"),
            ("rytas", "morning", "утро", "daiktavardis"),
            ("diena", "day / afternoon", "день", "daiktavardis"),
            ("vakaras", "evening", "вечер", "daiktavardis"),
            ("naktis", "night", "ночь", "daiktavardis"),
            ("po pietų", "p.m. / after noon", "после полудня / после обеда", "frazė"),
            ("prieš pietus", "a.m. / before noon", "до полудня / до обеда", "frazė"),
            # Verbs
            ("eiti, eina, ėjo", "to go (on foot)", "идти / ходить", "veiksmažodis"),
            ("skubėti, skuba, skubėjo", "to rush / to hurry", "торопиться / спешить", "veiksmažodis"),
            ("susitikti, susitinka, susitiko", "to meet", "встретиться / встречаться", "veiksmažodis"),
            ("važiuoti, važiuoja, važiavo", "to go (by transport)", "ехать / ездить", "veiksmažodis"),
            ("vėluoti, vėluoja, vėlavo", "to be late", "опаздывать", "veiksmažodis"),
            ("kartu", "together", "вместе", "prieveiksmis"),
        ],
    },
    {
        "title": "5. Čia mano šeima",
        "description": "Family, relatives and pets (Žodynas)",
        "words": [
            # People
            ("vaikinas", "young man / boyfriend", "парень / молодой человек", "daiktavardis"),
            ("mergina", "young woman / girlfriend", "девушка", "daiktavardis"),
            ("žmogus", "person / human", "человек", "daiktavardis"),
            ("vyras", "man / husband", "мужчина / муж", "daiktavardis"),
            ("moteris", "woman", "женщина", "daiktavardis"),
            ("berniukas", "boy", "мальчик", "daiktavardis"),
            ("mergaitė", "girl", "девочка", "daiktavardis"),
            ("vaikas", "child", "ребёнок", "daiktavardis"),
            ("mokinys / mokinė", "schoolboy / schoolgirl", "ученик / ученица", "daiktavardis"),
            # Family
            ("šeima", "family", "семья", "daiktavardis"),
            ("tėvai", "parents", "родители", "daiktavardis"),
            ("tėvas / tėtis", "father / daddy", "отец / папа", "daiktavardis"),
            ("motina / mama", "mother / mummy", "мать / мама", "daiktavardis"),
            ("žmona", "wife", "жена", "daiktavardis"),
            ("duktė", "daughter", "дочь", "daiktavardis"),
            ("sūnus", "son", "сын", "daiktavardis"),
            ("sesuo", "sister", "сестра", "daiktavardis"),
            ("brolis", "brother", "брат", "daiktavardis"),
            ("senelis", "grandfather", "дедушка", "daiktavardis"),
            ("senelė / močiutė", "grandmother", "бабушка", "daiktavardis"),
            ("anūkas / anūkė", "grandson / granddaughter", "внук / внучка", "daiktavardis"),
            # Relatives
            ("giminės", "relatives", "родственники", "daiktavardis"),
            ("teta", "aunt", "тётя", "daiktavardis"),
            ("dėdė", "uncle", "дядя", "daiktavardis"),
            ("pusbrolis / pusseserė", "cousin (m./f.)", "двоюродный брат / двоюродная сестра", "daiktavardis"),
            ("dukterėčia", "niece", "племянница", "daiktavardis"),
            ("sūnėnas", "nephew", "племянник", "daiktavardis"),
            # Marital status
            ("vedęs", "married (man)", "женатый", "būdvardis"),
            ("ištekėjusi", "married (woman)", "замужняя", "būdvardis"),
            ("išsiskyręs / išsiskyrusi", "divorced (m./f.)", "разведённый / разведённая", "būdvardis"),
            ("miręs / mirusi", "deceased (m./f.)", "умерший / умершая", "būdvardis"),
            # Pets
            ("naminis gyvūnas", "pet", "домашнее животное", "daiktavardis"),
            ("katė", "cat", "кошка", "daiktavardis"),
            ("šuo", "dog", "собака", "daiktavardis"),
            # Demonstratives
            ("šis / ši", "this (m./f.)", "этот / эта", "įvardis"),
            ("šie / šios", "these (m./f.)", "эти", "įvardis"),
            ("tas / ta", "that (m./f.)", "тот / та", "įvardis"),
            ("tie / tos", "those (m./f.)", "те", "įvardis"),
            # Interests
            ("muzika", "music", "музыка", "daiktavardis"),
            ("literatūra", "literature", "литература", "daiktavardis"),
            ("sportas", "sport", "спорт", "daiktavardis"),
            # Verbs
            ("mylėti, myli, mylėjo", "to love", "любить", "veiksmažodis"),
            ("sėdėti, sėdi, sėdėjo", "to sit", "сидеть", "veiksmažodis"),
            ("stovėti, stovi, stovėjo", "to stand", "стоять", "veiksmažodis"),
            ("turėti, turi, turėjo", "to have", "иметь", "veiksmažodis"),
            ("žiūrėti, žiūri, žiūrėjo", "to look / to watch", "смотреть", "veiksmažodis"),
            ("mėgti, mėgsta, mėgo", "to like", "любить / нравиться", "veiksmažodis"),
            ("sportuoti, sportuoja, sportavo", "to do sports", "заниматься спортом", "veiksmažodis"),
            ("vaikščioti, vaikščioja, vaikščiojo", "to walk", "гулять / ходить пешком", "veiksmažodis"),
        ],
    },
    {
        "title": "6. Mano sesers vardas yra Lina",
        "description": "Adjectives and descriptions (Žodynas)",
        "words": [
            ("aukštas / aukšta", "tall / high", "высокий / высокая", "būdvardis"),
            ("draugiškas / draugiška", "friendly", "дружелюбный / дружелюбная", "būdvardis"),
            ("geras / gera", "good / kind", "хороший / хорошая", "būdvardis"),
            ("jaunas / jauna", "young", "молодой / молодая", "būdvardis"),
            ("linksmas / linksma", "cheerful / happy", "весёлый / весёлая", "būdvardis"),
            ("liūdnas / liūdna", "sad", "грустный / грустная", "būdvardis"),
            ("mažas / maža", "small / little", "маленький / маленькая", "būdvardis"),
            ("mielas / miela", "dear / sweet / nice", "милый / милая", "būdvardis"),
            ("protingas / protinga", "smart / intelligent", "умный / умная", "būdvardis"),
            ("senas / sena", "old", "старый / старая", "būdvardis"),
            ("žemas / žema", "short / low", "низкий / низкая", "būdvardis"),
            ("gražus / graži", "beautiful / handsome / pretty", "красивый / красивая", "būdvardis"),
            ("įdomus / įdomi", "interesting", "интересный / интересная", "būdvardis"),
            ("malonus / maloni", "nice / pleasant", "приятный / приятная", "būdvardis"),
            ("puikus / puiki", "excellent / great", "отличный / отличная", "būdvardis"),
            ("šviesus / šviesi", "blond / light", "светлый / светлая", "būdvardis"),
            ("tamsus / tamsi", "dark", "тёмный / тёмная", "būdvardis"),
            ("didelis / didelė", "big / large", "большой / большая", "būdvardis"),
            ("vidurinis / vidurinė", "middle", "средний / средняя", "būdvardis"),
            ("jaunesnis / jaunesnė", "younger", "моложе / младший / младшая", "būdvardis"),
            ("jauniausias / jauniausia", "youngest", "самый младший / самая младшая", "būdvardis"),
            ("vyresnis / vyresnė", "older / elder", "старший / старшая", "būdvardis"),
            ("vyriausias / vyriausia", "oldest / senior", "самый старший / самая старшая", "būdvardis"),
        ],
    },
    {
        "title": "7. Labai skanu!",
        "description": "Food, drinks and meals (Žodynas)",
        "words": [
            # Dairy
            ("pienas", "milk", "молоко", "daiktavardis"),
            ("grietinė", "sour cream", "сметана", "daiktavardis"),
            ("jogurtas", "yogurt", "йогурт", "daiktavardis"),
            ("kefyras", "kefir", "кефир", "daiktavardis"),
            ("sūris", "cheese", "сыр", "daiktavardis"),
            ("sviestas", "butter", "масло", "daiktavardis"),
            ("varškė", "curd / cottage cheese", "творог", "daiktavardis"),
            # Bread & sweets
            ("duona", "bread", "хлеб", "daiktavardis"),
            ("juoda duona", "brown bread / rye bread", "чёрный хлеб", "daiktavardis"),
            ("šviesi duona", "white bread", "белый хлеб", "daiktavardis"),
            ("batonas", "long loaf / baguette", "батон", "daiktavardis"),
            ("bandelė", "roll / bun", "булочка", "daiktavardis"),
            ("medus", "honey", "мёд", "daiktavardis"),
            ("pyragas", "pie / cake", "пирог", "daiktavardis"),
            ("šokoladas", "chocolate", "шоколад", "daiktavardis"),
            ("spurga", "doughnut", "пончик", "daiktavardis"),
            ("tortas", "cake / gateau", "торт", "daiktavardis"),
            ("saldumynai", "sweets / candy", "сладости", "daiktavardis"),
            # Eggs & sandwiches
            ("kiaušinis", "egg", "яйцо", "daiktavardis"),
            ("sumuštinis", "sandwich", "бутерброд", "daiktavardis"),
            ("košė", "porridge", "каша", "daiktavardis"),
            # Meat & fish
            ("mėsa", "meat", "мясо", "daiktavardis"),
            ("jautiena", "beef", "говядина", "daiktavardis"),
            ("kalakutiena", "turkey", "индейка", "daiktavardis"),
            ("kiauliena", "pork", "свинина", "daiktavardis"),
            ("vištiena", "chicken", "курица", "daiktavardis"),
            ("dešra", "sausage", "колбаса", "daiktavardis"),
            ("dešrelės", "sausages / frankfurters", "сосиски", "daiktavardis"),
            ("kumpis", "ham", "ветчина", "daiktavardis"),
            ("žuvis", "fish", "рыба", "daiktavardis"),
            # Meals
            ("pusryčiai", "breakfast", "завтрак", "daiktavardis"),
            ("pietūs", "lunch / dinner", "обед", "daiktavardis"),
            ("vakarienė", "supper / dinner", "ужин", "daiktavardis"),
            # Drinks
            ("gėrimai", "drinks / beverages", "напитки", "daiktavardis"),
            ("vanduo", "water", "вода", "daiktavardis"),
            ("arbata", "tea", "чай", "daiktavardis"),
            ("kava", "coffee", "кофе", "daiktavardis"),
            ("gira", "kvass", "квас", "daiktavardis"),
            ("sultys", "juice", "сок", "daiktavardis"),
            # Adjectives
            ("alkanas / alkana", "hungry", "голодный / голодная", "būdvardis"),
            ("sotus / soti", "full / satisfied", "сытый / сытая", "būdvardis"),
            ("skanus / skani", "delicious / tasty", "вкусный / вкусная", "būdvardis"),
            ("šiltas / šilta", "warm", "тёплый / тёплая", "būdvardis"),
            ("šaltas / šalta", "cold", "холодный / холодная", "būdvardis"),
            ("karštas / karšta", "hot", "горячий / горячая", "būdvardis"),
            ("keptas / kepta", "baked / fried / roasted", "жареный / жареная", "būdvardis"),
            ("virtas / virta", "boiled / cooked", "варёный / варёная", "būdvardis"),
            ("juodas / juoda", "black", "чёрный / чёрная", "būdvardis"),
            # Verbs
            ("patikti, patinka, patiko", "to like / to please", "нравиться", "veiksmažodis"),
            ("norėti, nori, norėjo", "to want", "хотеть", "veiksmažodis"),
            ("valgyti, valgo, valgė", "to eat", "есть / кушать", "veiksmažodis"),
            ("gerti, geria, gėrė", "to drink", "пить", "veiksmažodis"),
            ("ragauti, ragauja, ragavo", "to taste / to try", "пробовать", "veiksmažodis"),
            ("imti, ima, ėmė", "to take", "брать", "veiksmažodis"),
            ("paduoti, paduoda, padavė", "to pass / to hand", "передать / подать", "veiksmažodis"),
            ("įdėti, įdeda, įdėjo", "to put (in)", "положить / добавить", "veiksmažodis"),
            ("įpilti, įpila, įpylė", "to pour (in)", "налить", "veiksmažodis"),
            ("pusryčiauti, pusryčiauja, pusryčiavo", "to have breakfast", "завтракать", "veiksmažodis"),
            ("pietauti, pietauja, pietavo", "to have lunch", "обедать", "veiksmažodis"),
            ("vakarieniauti, vakarieniauja, vakarieniavo", "to have supper", "ужинать", "veiksmažodis"),
        ],
    },
    {
        "title": "8. Šiandien eisiu į turgų",
        "description": "Market, vegetables, fruit and shopping (Žodynas)",
        "words": [
            # Market
            ("turgus", "market", "рынок", "daiktavardis"),
            ("pardavėjas / pardavėja", "seller / vendor (m./f.)", "продавец / продавщица", "daiktavardis"),
            ("gabaliukas / gabalėlis", "piece / bit", "кусочек", "daiktavardis"),
            ("kilogramas", "kilogram", "килограмм", "daiktavardis"),
            ("maišelis", "bag / carrier bag", "пакет / пакетик", "daiktavardis"),
            ("kaina", "price", "цена", "daiktavardis"),
            ("euras", "euro", "евро", "daiktavardis"),
            ("centas", "cent", "цент", "daiktavardis"),
            # Vegetables
            ("daržovės", "vegetables", "овощи", "daiktavardis"),
            ("agurkas", "cucumber", "огурец", "daiktavardis"),
            ("baklažanas", "aubergine / eggplant", "баклажан", "daiktavardis"),
            ("burokėlis", "beetroot", "свёкла", "daiktavardis"),
            ("bulvė", "potato", "картофель / картошка", "daiktavardis"),
            ("cukinija", "courgette / zucchini", "кабачок", "daiktavardis"),
            ("česnakas", "garlic", "чеснок", "daiktavardis"),
            ("kopūstas", "cabbage", "капуста", "daiktavardis"),
            ("moliūgas", "pumpkin", "тыква", "daiktavardis"),
            ("morka", "carrot", "морковь", "daiktavardis"),
            ("pomidoras", "tomato", "помидор", "daiktavardis"),
            ("pupelės", "beans", "фасоль", "daiktavardis"),
            ("svogūnas", "onion", "лук", "daiktavardis"),
            ("žirniai", "peas", "горох / горошек", "daiktavardis"),
            # Berries
            ("uogos", "berries", "ягоды", "daiktavardis"),
            ("avietės", "raspberries", "малина", "daiktavardis"),
            ("braškės", "strawberries", "клубника", "daiktavardis"),
            ("serbentai", "currants", "смородина", "daiktavardis"),
            ("vynuogės", "grapes", "виноград", "daiktavardis"),
            ("vyšnios", "cherries", "вишня", "daiktavardis"),
            # Nuts
            ("riešutai", "nuts", "орехи", "daiktavardis"),
            # Fruit
            ("vaisiai", "fruit", "фрукты", "daiktavardis"),
            ("apelsinas", "orange", "апельсин", "daiktavardis"),
            ("bananas", "banana", "банан", "daiktavardis"),
            ("citrina", "lemon", "лимон", "daiktavardis"),
            ("kriaušė", "pear", "груша", "daiktavardis"),
            ("obuolys", "apple", "яблоко", "daiktavardis"),
            # Spices
            ("prieskoniai", "spices / seasoning", "специи / приправы", "daiktavardis"),
            ("bazilikai", "basil", "базилик", "daiktavardis"),
            ("kmynai", "caraway seeds", "тмин", "daiktavardis"),
            ("krapai", "dill", "укроп", "daiktavardis"),
            ("lauro lapai", "bay leaves", "лавровый лист", "daiktavardis"),
            ("mėtos", "mint", "мята", "daiktavardis"),
            ("petražolės", "parsley", "петрушка", "daiktavardis"),
            ("pipirai", "pepper", "перец", "daiktavardis"),
            ("raudonėliai", "oregano", "орегано", "daiktavardis"),
            # Other food
            ("sriuba", "soup", "суп", "daiktavardis"),
            ("salotos", "salad", "салат", "daiktavardis"),
            # Adjectives
            ("saldus / saldi", "sweet", "сладкий / сладкая", "būdvardis"),
            ("rūgštus / rūgšti", "sour / acidic", "кислый / кислая", "būdvardis"),
            ("šviežias / šviežia", "fresh", "свежий / свежая", "būdvardis"),
            ("riebus / riebi", "rich / fatty", "жирный / жирная", "būdvardis"),
            ("rūkytas / rūkyta", "smoked", "копчёный / копчёная", "būdvardis"),
            ("žalias / žalia", "raw / green", "сырой / зелёный", "būdvardis"),
            # Colours
            ("baltas / balta", "white", "белый / белая", "būdvardis"),
            ("geltonas / geltona", "yellow", "жёлтый / жёлтая", "būdvardis"),
            ("mėlynas / mėlyna", "blue", "синий / голубой", "būdvardis"),
            ("raudonas / raudona", "red", "красный / красная", "būdvardis"),
            # Verbs
            ("daryti, daro, darė", "to do / to make", "делать", "veiksmažodis"),
            ("kepti, kepa, kepė", "to fry / to bake / to grill", "жарить / печь", "veiksmažodis"),
            ("virti, verda, virė", "to boil / to cook", "варить / готовить", "veiksmažodis"),
            ("duoti, duoda, davė", "to give", "давать / дать", "veiksmažodis"),
            ("pirkti, perka, pirko", "to buy", "покупать", "veiksmažodis"),
        ],
    },
    {
        "title": "9. Norėčiau kavos",
        "description": "Cafe, restaurant and Lithuanian dishes (Žodynas)",
        "words": [
            # Places
            ("kavinė", "cafe", "кафе", "daiktavardis"),
            ("kepyklėlė", "bakery", "пекарня", "daiktavardis"),
            ("restoranas", "restaurant", "ресторан", "daiktavardis"),
            ("baras", "bar", "бар", "daiktavardis"),
            ("picerija", "pizzeria", "пиццерия", "daiktavardis"),
            ("padavėjas / padavėja", "waiter / waitress", "официант / официантка", "daiktavardis"),
            # Menu & service
            ("meniu", "menu", "меню", "daiktavardis"),
            ("dienos pietūs", "set lunch / lunch special", "бизнес-ланч / обед дня", "daiktavardis"),
            ("staliukas", "table", "столик", "daiktavardis"),
            ("sąskaita", "bill / check", "счёт", "daiktavardis"),
            ("paprastai", "usually", "обычно", "prieveiksmis"),
            ("patiekalas", "dish / course", "блюдо", "daiktavardis"),
            # Soups & salads
            ("sriuba", "soup", "суп", "daiktavardis"),
            ("dienos sriuba", "soup of the day", "суп дня", "daiktavardis"),
            ("daržovių sriuba", "vegetable soup", "овощной суп", "daiktavardis"),
            ("grybų sriuba", "mushroom soup", "грибной суп", "daiktavardis"),
            ("burokėlių sriuba", "beetroot soup", "свекольный суп", "daiktavardis"),
            ("salotos", "salad", "салат", "daiktavardis"),
            ("daržovių salotos", "vegetable salad", "овощной салат", "daiktavardis"),
            ("pomidorų salotos", "tomato salad", "салат из помидоров", "daiktavardis"),
            ("kopūstų salotos", "cabbage salad", "капустный салат", "daiktavardis"),
            ("lietuviškos salotos", "Lithuanian salad (Olivier)", "литовский салат (оливье)", "daiktavardis"),
            # Eggs & bread
            ("omletas", "omelette", "омлет", "daiktavardis"),
            ("kiaušinienė", "fried eggs", "яичница", "daiktavardis"),
            ("kiaušinienė su šonine", "fried eggs with bacon", "яичница с беконом", "daiktavardis"),
            ("sumuštinis su kumpiu ir salotomis", "sandwich with ham and lettuce", "бутерброд с ветчиной и салатом", "daiktavardis"),
            # Main courses
            ("kepsnys", "roast / grilled meat", "жаркое / отбивная", "daiktavardis"),
            ("vištienos kepsnys", "chicken roast", "куриная отбивная", "daiktavardis"),
            ("kiaulienos kepsnys", "pork roast", "свиная отбивная", "daiktavardis"),
            ("jautienos kepsnys", "beef roast", "говяжья отбивная", "daiktavardis"),
            ("pica", "pizza", "пицца", "daiktavardis"),
            # Pancakes & pasta
            ("blynai", "pancakes", "блины / оладьи", "daiktavardis"),
            ("bulvių blynai", "potato pancakes", "картофельные блины / драники", "daiktavardis"),
            ("blynelis", "crepe", "блинчик", "daiktavardis"),
            ("blyneliai su sūriu", "crepes with cheese", "блинчики с сыром", "daiktavardis"),
            ("blyneliai su obuoliais", "crepes with apples", "блинчики с яблоками", "daiktavardis"),
            ("blyneliai su uogiene", "crepes with jam", "блинчики с вареньем", "daiktavardis"),
            ("makaronai", "pasta", "паста / макароны", "daiktavardis"),
            ("ryžiai", "rice", "рис", "daiktavardis"),
            ("košė", "porridge", "каша", "daiktavardis"),
            ("avižinė košė", "oat porridge", "овсяная каша", "daiktavardis"),
            ("grikių košė", "buckwheat porridge", "гречневая каша", "daiktavardis"),
            # Desserts
            ("desertas", "dessert", "десерт", "daiktavardis"),
            ("ledai", "ice cream", "мороженое", "daiktavardis"),
            ("pyragaitis", "pastry", "пирожное", "daiktavardis"),
            ("tortas", "cake", "торт", "daiktavardis"),
            # Condiments
            ("actas", "vinegar", "уксус", "daiktavardis"),
            ("aliejus", "oil", "масло (растительное)", "daiktavardis"),
            ("cukrus", "sugar", "сахар", "daiktavardis"),
            ("druska", "salt", "соль", "daiktavardis"),
            ("garstyčios", "mustard", "горчица", "daiktavardis"),
            ("krienai", "horseradish", "хрен", "daiktavardis"),
            ("majonezas", "mayonnaise", "майонез", "daiktavardis"),
            ("padažas", "sauce / dressing", "соус", "daiktavardis"),
            ("uogienė", "jam", "варенье / джем", "daiktavardis"),
            # Drinks
            ("gazuotas vanduo", "soda water / sparkling water", "газированная вода", "daiktavardis"),
            ("negazuotas vanduo", "still water", "негазированная вода", "daiktavardis"),
            ("juoda arbata", "black tea", "чёрный чай", "daiktavardis"),
            ("žalia arbata", "green tea", "зелёный чай", "daiktavardis"),
            ("vaisinė arbata", "fruit tea", "фруктовый чай", "daiktavardis"),
            ("žolelių arbata", "herbal tea", "травяной чай", "daiktavardis"),
            ("mėtų arbata", "mint tea", "мятный чай", "daiktavardis"),
            ("kokteilis", "cocktail / milkshake", "коктейль", "daiktavardis"),
            ("obuolių sultys", "apple juice", "яблочный сок", "daiktavardis"),
            ("apelsinų sultys", "orange juice", "апельсиновый сок", "daiktavardis"),
            ("ananasų sultys", "pineapple juice", "ананасовый сок", "daiktavardis"),
            ("vynuogių sultys", "grape juice", "виноградный сок", "daiktavardis"),
            ("morkų sultys", "carrot juice", "морковный сок", "daiktavardis"),
            ("pomidorų sultys", "tomato juice", "томатный сок", "daiktavardis"),
            ("gira", "kvass", "квас", "daiktavardis"),
            ("šakotis", "spit cake (traditional)", "шакотис (литовский пирог)", "daiktavardis"),
            # Lithuanian dishes
            ("šaltibarščiai", "cold beetroot soup", "холодный свекольный суп", "lietuviškas patiekalas"),
            ("cepelinai", "potato dumplings (with meat/curd/mushrooms)", "цепелинai (картофельные клёцки)", "lietuviškas patiekalas"),
            ("medaus tortas", "honey cake", "медовый торт", "lietuviškas patiekalas"),
            # Adjectives
            ("aštrus / aštri", "spicy / hot", "острый / острая", "būdvardis"),
            ("švelnus / švelni", "mild / gentle", "мягкий / мягкая", "būdvardis"),
            ("sūrus / sūri", "salty", "солёный / солёная", "būdvardis"),
        ],
    },
]


def seed():
    with Session(engine) as session:
        # Remove all existing data (order matters due to foreign keys)
        from models import UserWordProgress
        for row in session.exec(select(UserWordProgress)).all():
            session.delete(row)

        for row in session.exec(select(WordListItem)).all():
            session.delete(row)

        for row in session.exec(select(Word)).all():
            session.delete(row)

        for row in session.exec(select(WordList)).all():
            session.delete(row)

        session.commit()
        print("Cleared existing word lists, words and items.")

        for list_data in WORD_LISTS:
            wl = WordList(
                title=list_data["title"],
                description=list_data["description"],
            )
            session.add(wl)
            session.flush()  # get wl.id

            for position, (lt, en, ru, hint) in enumerate(list_data["words"]):
                word = Word(
                    lithuanian=lt,
                    translation_en=en,
                    translation_ru=ru,
                    hint=hint,
                )
                session.add(word)
                session.flush()  # get word.id

                item = WordListItem(
                    word_list_id=wl.id,
                    word_id=word.id,
                    position=position,
                )
                session.add(item)

        session.commit()
        print(f"Seeded {len(WORD_LISTS)} word lists.")
        for ld in WORD_LISTS:
            print(f"  - {ld['title']}: {len(ld['words'])} words")


if __name__ == "__main__":
    seed()
